require("dotenv").config()
const mongoose = require("mongoose")
const Attraction = require("../models/attraction")

const attractions = [
  {
    country: "Pakistan",
    city: "Lahore",
    name: "Badshahi Mosque",
    picture: "https://images.unsplash.com/photo-1601042825451-36e7b8a5f5d6",
    description:
      "One of the largest mosques in the world, built during the Mughal era.",
  },
  {
    country: "Pakistan",
    city: "Lahore",
    name: "Lahore Fort",
    picture: "https://images.unsplash.com/photo-1624958723474-6d4a6f5c8e1a",
    description: "Historic Mughal fort and UNESCO World Heritage site.",
  },
  {
    country: "Pakistan",
    city: "Lahore",
    name: "Shalimar Gardens",
    picture: "https://images.unsplash.com/photo-1593697820672-b4c7f8d9e1a2",
    description: "Mughal-era gardens known for their symmetry and fountains.",
  },
  {
    country: "Pakistan",
    city: "Karachi",
    name: "Clifton Beach",
    picture: "https://images.unsplash.com/photo-1588581939864-064e6b68e3a1",
    description: "Popular beach along the Arabian Sea.",
  },
  {
    country: "Pakistan",
    city: "Karachi",
    name: "Mazar-e-Quaid",
    picture: "https://images.unsplash.com/photo-1619451334791-9e0e6c4b9d2f",
    description: "Mausoleum of Pakistan’s founder, Muhammad Ali Jinnah.",
  },
  {
    country: "Pakistan",
    city: "Karachi",
    name: "Pakistan Maritime Museum",
    picture: "https://images.unsplash.com/photo-1600788907416-456f6a4e3c9b",
    description: "Naval museum showcasing maritime history.",
  },
  {
    country: "Pakistan",
    city: "Islamabad",
    name: "Faisal Mosque",
    picture: "https://images.unsplash.com/photo-1603791452906-bcbb8a4f9a2e",
    description: "Iconic modern mosque set against Margalla Hills.",
  },
  {
    country: "Pakistan",
    city: "Islamabad",
    name: "Daman-e-Koh",
    picture: "https://images.unsplash.com/photo-1598257006458-087fbe7a6c1e",
    description: "Hilltop viewpoint overlooking Islamabad.",
  },
  {
    country: "Pakistan",
    city: "Islamabad",
    name: "Pakistan Monument",
    picture: "https://images.unsplash.com/photo-1613924601028-8b5c3a1e7d4f",
    description: "National monument symbolizing unity.",
  },
  {
    country: "France",
    city: "Paris",
    name: "Eiffel Tower",
    picture: "https://images.unsplash.com/photo-1549640376-8e8d5a39a23a",
    description: "An iconic iron tower offering panoramic views of Paris.",
  },
  {
    country: "France",
    city: "Paris",
    name: "Louvre Museum",
    picture: "https://images.unsplash.com/photo-1529429617124-a32e7d3c9b2d",
    description: "The world’s largest art museum and historic monument.",
  },
  {
    country: "France",
    city: "Nice",
    name: "Promenade des Anglais",
    picture: "https://images.unsplash.com/photo-1505731132164-cca903a4f4b0",
    description: "A scenic seafront boulevard along the Mediterranean coast.",
  },
  {
    country: "France",
    city: "Nice",
    name: "Castle Hill",
    picture: "https://images.unsplash.com/photo-1598890777032-bde8358e32f8",
    description: "A hilltop park offering panoramic views of Nice.",
  },
  {
    country: "Italy",
    city: "Rome",
    name: "Colosseum",
    picture: "https://images.unsplash.com/photo-1552832230-c0197dd311b5",
    description: "An ancient Roman amphitheater known for gladiator battles.",
  },
  {
    country: "Italy",
    city: "Rome",
    name: "Vatican City",
    picture: "https://images.unsplash.com/photo-1529260830199-42c24126f198",
    description: "Home to the Pope and famous religious art and architecture.",
  },
  {
    country: "Italy",
    city: "Venice",
    name: "Grand Canal",
    picture: "https://images.unsplash.com/photo-1509358271058-acd22cc93898",
    description: "The main waterway of Venice lined with historic buildings.",
  },
  {
    country: "Italy",
    city: "Venice",
    name: "St. Mark’s Square",
    picture: "https://images.unsplash.com/photo-1514890547357-a9ee288728e0",
    description: "A famous public square surrounded by landmarks.",
  },
  {
    country: "Japan",
    city: "Tokyo",
    name: "Shibuya Crossing",
    picture: "https://images.unsplash.com/photo-1549693578-d683be217e58",
    description: "One of the busiest pedestrian crossings in the world.",
  },
  {
    country: "Japan",
    city: "Tokyo",
    name: "Tokyo Tower",
    picture: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf",
    description: "A communications tower offering city views.",
  },
  {
    country: "Japan",
    city: "Kyoto",
    name: "Fushimi Inari Shrine",
    picture: "https://images.unsplash.com/photo-1526481280691-3d3a6c7f47d5",
    description: "Famous for its thousands of red torii gates.",
  },
  {
    country: "Japan",
    city: "Kyoto",
    name: "Kinkaku-ji",
    picture: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9",
    description: "A Zen temple covered in gold leaf.",
  },
  {
    country: "United States",
    city: "New York",
    name: "Statue of Liberty",
    picture: "https://images.unsplash.com/photo-1534447677768-be436bb09401",
    description: "A symbol of freedom and democracy.",
  },
  {
    country: "United States",
    city: "New York",
    name: "Central Park",
    picture: "https://images.unsplash.com/photo-1534854638093-bada1813ca19",
    description: "A large urban park in the heart of Manhattan.",
  },
  {
    country: "United States",
    city: "San Francisco",
    name: "Golden Gate Bridge",
    picture: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29",
    description: "A famous red suspension bridge.",
  },
  {
    country: "United States",
    city: "San Francisco",
    name: "Alcatraz Island",
    picture: "https://images.unsplash.com/photo-1506976785307-8732e854ad03",
    description: "Historic island prison turned tourist attraction.",
  },
  {
    country: "Australia",
    city: "Sydney",
    name: "Sydney Opera House",
    picture: "https://images.unsplash.com/photo-1506973035872-a4f23f3ba3db",
    description: "A world-famous performing arts center.",
  },
  {
    country: "Australia",
    city: "Sydney",
    name: "Bondi Beach",
    picture: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    description: "A popular beach known for surfing.",
  },
  {
    country: "Australia",
    city: "Melbourne",
    name: "Federation Square",
    picture: "https://images.unsplash.com/photo-1526481280691-d6a1d5b3b12a",
    description: "A cultural hub with events and museums.",
  },
  {
    country: "Australia",
    city: "Melbourne",
    name: "Great Ocean Road",
    picture: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    description: "A scenic coastal drive with stunning views.",
  },
  {
    country: "Argentina",
    city: "Buenos Aires",
    name: "Obelisco",
    picture: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad",
    description: "Famous city landmark.",
  },
  {
    country: "Argentina",
    city: "Buenos Aires",
    name: "La Boca",
    picture: "https://images.unsplash.com/photo-1548266652-5a6b7c8d9e0f",
    description: "Colorful neighborhood.",
  },
  {
    country: "Argentina",
    city: "Buenos Aires",
    name: "Teatro Colón",
    picture: "https://images.unsplash.com/photo-1520975922284-7b6c5d4e3f2a",
    description: "Famous opera house.",
  },
  {
    country: "Argentina",
    city: "Mendoza",
    name: "Aconcagua",
    picture: "https://images.unsplash.com/photo-1549924231-2a3b4c5d6e7f",
    description: "Highest mountain in South America.",
  },
  {
    country: "Argentina",
    city: "Mendoza",
    name: "Bodega Norton",
    picture: "https://images.unsplash.com/photo-1520975922284-8b456906c813",
    description: "Famous winery.",
  },
  {
    country: "Argentina",
    city: "Mendoza",
    name: "Plaza Independencia",
    picture: "https://images.unsplash.com/photo-1600703136783-4a5b6c7d8e9f",
    description: "Central square in Mendoza.",
  },
  {
    country: "Egypt",
    city: "Cairo",
    name: "Pyramids of Giza",
    picture: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad",
    description: "Ancient pyramids.",
  },
  {
    country: "Egypt",
    city: "Cairo",
    name: "Egyptian Museum",
    picture: "https://images.unsplash.com/photo-1548266652-5a6b7c8d9e0f",
    description: "Museum with Egyptian antiquities.",
  },
  {
    country: "Egypt",
    city: "Cairo",
    name: "Khan el-Khalili",
    picture: "https://images.unsplash.com/photo-1520975922284-7b6c5d4e3f2a",
    description: "Famous bazaar.",
  },
  {
    country: "Egypt",
    city: "Luxor",
    name: "Valley of the Kings",
    picture: "https://images.unsplash.com/photo-1549924231-2a3b4c5d6e7f",
    description: "Ancient burial site.",
  },
  {
    country: "Egypt",
    city: "Luxor",
    name: "Karnak Temple",
    picture: "https://images.unsplash.com/photo-1520975922284-8b456906c813",
    description: "Large temple complex.",
  },
  {
    country: "Egypt",
    city: "Luxor",
    name: "Luxor Temple",
    picture: "https://images.unsplash.com/photo-1600703136783-4a5b6c7d8e9f",
    description: "Ancient temple along Nile.",
  },
  {
    country: "South Korea",
    city: "Seoul",
    name: "Gyeongbokgung Palace",
    picture: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad",
    description: "Historic palace.",
  },
  {
    country: "South Korea",
    city: "Seoul",
    name: "N Seoul Tower",
    picture: "https://images.unsplash.com/photo-1548266652-5a6b7c8d9e0f",
    description: "Famous observation tower.",
  },
  {
    country: "South Korea",
    city: "Seoul",
    name: "Myeongdong",
    picture: "https://images.unsplash.com/photo-1520975922284-7b6c5d4e3f2a",
    description: "Shopping district.",
  },
  {
    country: "South Korea",
    city: "Busan",
    name: "Haeundae Beach",
    picture: "https://images.unsplash.com/photo-1549924231-2a3b4c5d6e7f",
    description: "Popular beach.",
  },
  {
    country: "South Korea",
    city: "Busan",
    name: "Gamcheon Culture Village",
    picture: "https://images.unsplash.com/photo-1520975922284-8b456906c813",
    description: "Colorful hillside village.",
  },
  {
    country: "South Korea",
    city: "Busan",
    name: "Jagalchi Fish Market",
    picture: "https://images.unsplash.com/photo-1600703136783-4a5b6c7d8e9f",
    description: "Famous seafood market.",
  },
  {
    country: "Turkey",
    city: "Istanbul",
    name: "Hagia Sophia",
    picture: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad",
    description: "Historic mosque and museum.",
  },
  {
    country: "Turkey",
    city: "Istanbul",
    name: "Blue Mosque",
    picture: "https://images.unsplash.com/photo-1548266652-5a6b7c8d9e0f",
    description: "Famous mosque.",
  },
  {
    country: "Turkey",
    city: "Istanbul",
    name: "Grand Bazaar",
    picture: "https://images.unsplash.com/photo-1520975922284-7b6c5d4e3f2a",
    description: "Historic covered market.",
  },
  {
    country: "Turkey",
    city: "Cappadocia",
    name: "Hot Air Balloon Rides",
    picture: "https://images.unsplash.com/photo-1549924231-2a3b4c5d6e7f",
    description: "Famous for ballooning over rock formations.",
  },
  {
    country: "Turkey",
    city: "Cappadocia",
    name: "Göreme Open-Air Museum",
    picture: "https://images.unsplash.com/photo-1520975922284-8b456906c813",
    description: "Rock-cut churches.",
  },
  {
    country: "Turkey",
    city: "Cappadocia",
    name: "Fairy Chimneys",
    picture: "https://images.unsplash.com/photo-1600703136783-4a5b6c7d8e9f",
    description: "Unique rock formations.",
  },
  {
    country: "Thailand",
    city: "Bangkok",
    name: "Grand Palace",
    picture: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad",
    description: "Royal palace complex.",
  },
  {
    country: "Thailand",
    city: "Bangkok",
    name: "Wat Pho",
    picture: "https://images.unsplash.com/photo-1548266652-5a6b7c8d9e0f",
    description: "Temple with reclining Buddha.",
  },
  {
    country: "Thailand",
    city: "Bangkok",
    name: "Chatuchak Market",
    picture: "https://images.unsplash.com/photo-1520975922284-7b6c5d4e3f2a",
    description: "Famous weekend market.",
  },
  {
    country: "Thailand",
    city: "Chiang Mai",
    name: "Doi Suthep Temple",
    picture: "https://images.unsplash.com/photo-1549924231-2a3b4c5d6e7f",
    description: "Temple on a mountain.",
  },
  {
    country: "Thailand",
    city: "Chiang Mai",
    name: "Old City Temples",
    picture: "https://images.unsplash.com/photo-1520975922284-8b456906c813",
    description: "Historic temples in old city.",
  },
  {
    country: "Thailand",
    city: "Chiang Mai",
    name: "Night Bazaar",
    picture: "https://images.unsplash.com/photo-1600703136783-4a5b6c7d8e9f",
    description: "Famous evening market.",
  },
  {
    country: "Greece",
    city: "Athens",
    name: "Acropolis",
    picture: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad",
    description: "Ancient citadel with historic ruins.",
  },
  {
    country: "Greece",
    city: "Athens",
    name: "Parthenon",
    picture: "https://images.unsplash.com/photo-1548266652-5a6b7c8d9e0f",
    description: "Iconic ancient Greek temple.",
  },
  {
    country: "Greece",
    city: "Athens",
    name: "Plaka",
    picture: "https://images.unsplash.com/photo-1520975922284-7b6c5d4e3f2a",
    description: "Historic old neighborhood.",
  },
  {
    country: "Greece",
    city: "Santorini",
    name: "Oia",
    picture: "https://images.unsplash.com/photo-1549924231-2a3b4c5d6e7f",
    description: "Famous sunset village.",
  },
  {
    country: "Greece",
    city: "Santorini",
    name: "Red Beach",
    picture: "https://images.unsplash.com/photo-1520975922284-8b456906c813",
    description: "Volcanic red sand beach.",
  },
  {
    country: "Greece",
    city: "Santorini",
    name: "Fira",
    picture: "https://images.unsplash.com/photo-1600703136783-4a5b6c7d8e9f",
    description: "Clifftop capital town.",
  },
  {
    country: "Portugal",
    city: "Lisbon",
    name: "Belém Tower",
    picture: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad",
    description: "Historic riverside tower.",
  },
  {
    country: "Portugal",
    city: "Lisbon",
    name: "Jerónimos Monastery",
    picture: "https://images.unsplash.com/photo-1548266652-5a6b7c8d9e0f",
    description: "UNESCO World Heritage monastery.",
  },
  {
    country: "Portugal",
    city: "Lisbon",
    name: "Alfama",
    picture: "https://images.unsplash.com/photo-1520975922284-7b6c5d4e3f2a",
    description: "Oldest district in Lisbon.",
  },
  {
    country: "Portugal",
    city: "Porto",
    name: "Dom Luís I Bridge",
    picture: "https://images.unsplash.com/photo-1549924231-2a3b4c5d6e7f",
    description: "Iconic double-deck bridge.",
  },
  {
    country: "Portugal",
    city: "Porto",
    name: "Ribeira",
    picture: "https://images.unsplash.com/photo-1520975922284-8b456906c813",
    description: "Historic riverside district.",
  },
  {
    country: "Portugal",
    city: "Porto",
    name: "Livraria Lello",
    picture: "https://images.unsplash.com/photo-1600703136783-4a5b6c7d8e9f",
    description: "Famous historic bookstore.",
  },
  {
    country: "Netherlands",
    city: "Amsterdam",
    name: "Anne Frank House",
    picture: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad",
    description: "Historic house museum.",
  },
  {
    country: "Netherlands",
    city: "Amsterdam",
    name: "Rijksmuseum",
    picture: "https://images.unsplash.com/photo-1548266652-5a6b7c8d9e0f",
    description: "National art museum.",
  },
  {
    country: "Netherlands",
    city: "Amsterdam",
    name: "Canals of Amsterdam",
    picture: "https://images.unsplash.com/photo-1520975922284-7b6c5d4e3f2a",
    description: "UNESCO-listed canals.",
  },
  {
    country: "Netherlands",
    city: "Rotterdam",
    name: "Cube Houses",
    picture: "https://images.unsplash.com/photo-1549924231-2a3b4c5d6e7f",
    description: "Unique architectural houses.",
  },
  {
    country: "Netherlands",
    city: "Rotterdam",
    name: "Erasmus Bridge",
    picture: "https://images.unsplash.com/photo-1520975922284-8b456906c813",
    description: "Modern cable-stayed bridge.",
  },
  {
    country: "Netherlands",
    city: "Rotterdam",
    name: "Markthal",
    picture: "https://images.unsplash.com/photo-1600703136783-4a5b6c7d8e9f",
    description: "Indoor food market.",
  },
  {
    country: "Sweden",
    city: "Stockholm",
    name: "Gamla Stan",
    picture: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad",
    description: "Medieval old town.",
  },
  {
    country: "Sweden",
    city: "Stockholm",
    name: "Vasa Museum",
    picture: "https://images.unsplash.com/photo-1548266652-5a6b7c8d9e0f",
    description: "17th-century warship museum.",
  },
  {
    country: "Sweden",
    city: "Stockholm",
    name: "Skansen",
    picture: "https://images.unsplash.com/photo-1520975922284-7b6c5d4e3f2a",
    description: "Open-air museum.",
  },
  {
    country: "Sweden",
    city: "Gothenburg",
    name: "Liseberg",
    picture: "https://images.unsplash.com/photo-1549924231-2a3b4c5d6e7f",
    description: "Popular amusement park.",
  },
  {
    country: "Sweden",
    city: "Gothenburg",
    name: "Haga",
    picture: "https://images.unsplash.com/photo-1520975922284-8b456906c813",
    description: "Historic neighborhood.",
  },
  {
    country: "Sweden",
    city: "Gothenburg",
    name: "Universeum",
    picture: "https://images.unsplash.com/photo-1600703136783-4a5b6c7d8e9f",
    description: "Science and nature center.",
  },
  {
    country: "Finland",
    city: "Helsinki",
    name: "Suomenlinna",
    picture: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad",
    description: "Sea fortress.",
  },
  {
    country: "Finland",
    city: "Helsinki",
    name: "Helsinki Cathedral",
    picture: "https://images.unsplash.com/photo-1548266652-5a6b7c8d9e0f",
    description: "Iconic white cathedral.",
  },
  {
    country: "Finland",
    city: "Helsinki",
    name: "Market Square",
    picture: "https://images.unsplash.com/photo-1520975922284-7b6c5d4e3f2a",
    description: "Harbor-side market.",
  },
  {
    country: "Finland",
    city: "Rovaniemi",
    name: "Santa Claus Village",
    picture: "https://images.unsplash.com/photo-1549924231-2a3b4c5d6e7f",
    description: "Official home of Santa Claus.",
  },
  {
    country: "Finland",
    city: "Rovaniemi",
    name: "Arktikum Museum",
    picture: "https://images.unsplash.com/photo-1520975922284-8b456906c813",
    description: "Arctic science museum.",
  },
  {
    country: "Finland",
    city: "Rovaniemi",
    name: "Northern Lights Tours",
    picture: "https://images.unsplash.com/photo-1600703136783-4a5b6c7d8e9f",
    description: "Aurora viewing experiences.",
  },
  {
    country: "Denmark",
    city: "Copenhagen",
    name: "Nyhavn",
    picture: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad",
    description: "Colorful 17th-century harbor district.",
  },
  {
    country: "Denmark",
    city: "Copenhagen",
    name: "Tivoli Gardens",
    picture: "https://images.unsplash.com/photo-1548266652-5a6b7c8d9e0f",
    description: "Historic amusement park.",
  },
  {
    country: "Denmark",
    city: "Copenhagen",
    name: "The Little Mermaid",
    picture: "https://images.unsplash.com/photo-1520975922284-7b6c5d4e3f2a",
    description: "Iconic bronze statue.",
  },
  {
    country: "Denmark",
    city: "Aarhus",
    name: "ARoS Art Museum",
    picture: "https://images.unsplash.com/photo-1549924231-2a3b4c5d6e7f",
    description: "Modern art museum with rainbow panorama.",
  },
  {
    country: "Denmark",
    city: "Aarhus",
    name: "Den Gamle By",
    picture: "https://images.unsplash.com/photo-1520975922284-8b456906c813",
    description: "Open-air historical town.",
  },
  {
    country: "Denmark",
    city: "Aarhus",
    name: "Aarhus Cathedral",
    picture: "https://images.unsplash.com/photo-1600703136783-4a5b6c7d8e9f",
    description: "Longest church in Denmark.",
  },
  {
    country: "Ireland",
    city: "Dublin",
    name: "Trinity College",
    picture: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad",
    description: "Historic university and Book of Kells.",
  },
  {
    country: "Ireland",
    city: "Dublin",
    name: "Guinness Storehouse",
    picture: "https://images.unsplash.com/photo-1548266652-5a6b7c8d9e0f",
    description: "Famous brewery museum.",
  },
  {
    country: "Ireland",
    city: "Dublin",
    name: "Temple Bar",
    picture: "https://images.unsplash.com/photo-1520975922284-7b6c5d4e3f2a",
    description: "Lively cultural quarter.",
  },
  {
    country: "Ireland",
    city: "Galway",
    name: "Eyre Square",
    picture: "https://images.unsplash.com/photo-1549924231-2a3b4c5d6e7f",
    description: "Central city square.",
  },
  {
    country: "Ireland",
    city: "Galway",
    name: "Spanish Arch",
    picture: "https://images.unsplash.com/photo-1520975922284-8b456906c813",
    description: "Historic city arch.",
  },
  {
    country: "Ireland",
    city: "Galway",
    name: "Salthill Promenade",
    picture: "https://images.unsplash.com/photo-1600703136783-4a5b6c7d8e9f",
    description: "Seaside walking promenade.",
  },
  {
    country: "Poland",
    city: "Warsaw",
    name: "Old Town",
    picture: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad",
    description: "Reconstructed historic center.",
  },
  {
    country: "Poland",
    city: "Warsaw",
    name: "Royal Castle",
    picture: "https://images.unsplash.com/photo-1548266652-5a6b7c8d9e0f",
    description: "Former Polish monarch residence.",
  },
  {
    country: "Poland",
    city: "Warsaw",
    name: "Łazienki Park",
    picture: "https://images.unsplash.com/photo-1520975922284-7b6c5d4e3f2a",
    description: "Largest park in Warsaw.",
  },
  {
    country: "Poland",
    city: "Kraków",
    name: "Wawel Castle",
    picture: "https://images.unsplash.com/photo-1549924231-2a3b4c5d6e7f",
    description: "Historic royal castle.",
  },
  {
    country: "Poland",
    city: "Kraków",
    name: "Main Market Square",
    picture: "https://images.unsplash.com/photo-1520975922284-8b456906c813",
    description: "Largest medieval square in Europe.",
  },
  {
    country: "Poland",
    city: "Kraków",
    name: "Kazimierz",
    picture: "https://images.unsplash.com/photo-1600703136783-4a5b6c7d8e9f",
    description: "Historic Jewish quarter.",
  },
  {
    country: "Czech Republic",
    city: "Prague",
    name: "Charles Bridge",
    picture: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad",
    description: "Historic stone bridge.",
  },
  {
    country: "Czech Republic",
    city: "Prague",
    name: "Prague Castle",
    picture: "https://images.unsplash.com/photo-1548266652-5a6b7c8d9e0f",
    description: "Largest ancient castle complex.",
  },
  {
    country: "Czech Republic",
    city: "Prague",
    name: "Old Town Square",
    picture: "https://images.unsplash.com/photo-1520975922284-7b6c5d4e3f2a",
    description: "Historic square with Astronomical Clock.",
  },
  {
    country: "Czech Republic",
    city: "Brno",
    name: "Špilberk Castle",
    picture: "https://images.unsplash.com/photo-1549924231-2a3b4c5d6e7f",
    description: "Hilltop fortress.",
  },
  {
    country: "Czech Republic",
    city: "Brno",
    name: "Villa Tugendhat",
    picture: "https://images.unsplash.com/photo-1520975922284-8b456906c813",
    description: "UNESCO modernist villa.",
  },
  {
    country: "Czech Republic",
    city: "Brno",
    name: "Cathedral of St. Peter and Paul",
    picture: "https://images.unsplash.com/photo-1600703136783-4a5b6c7d8e9f",
    description: "City landmark cathedral.",
  },
  {
    country: "Hungary",
    city: "Budapest",
    name: "Buda Castle",
    picture: "https://images.unsplash.com/photo-1549640376-89f79c36d95f",
    description: "Historic castle complex overlooking the Danube.",
  },
  {
    country: "Hungary",
    city: "Budapest",
    name: "Parliament Building",
    picture: "https://images.unsplash.com/photo-1526481280691-9063f45c4d5a",
    description: "Iconic neo-Gothic government building.",
  },
  {
    country: "Hungary",
    city: "Budapest",
    name: "Chain Bridge",
    picture: "https://images.unsplash.com/photo-1600172454520-1348f8c9c78d",
    description: "Famous bridge connecting Buda and Pest.",
  },
  {
    country: "Hungary",
    city: "Debrecen",
    name: "Great Reformed Church",
    picture: "https://images.unsplash.com/photo-1603694568452-9a7e8c6d4f1b",
    description: "Symbol of Hungarian Protestantism.",
  },
  {
    country: "Hungary",
    city: "Debrecen",
    name: "Nagyerdő Park",
    picture: "https://images.unsplash.com/photo-1587300003388-59208cc962cb",
    description: "Large park with thermal baths.",
  },
  {
    country: "Hungary",
    city: "Debrecen",
    name: "Déri Museum",
    picture: "https://images.unsplash.com/photo-1599407380126-1c1c5f3e7d8b",
    description: "Museum of art and archaeology.",
  },
  {
    country: "Slovakia",
    city: "Bratislava",
    name: "Bratislava Castle",
    picture: "https://images.unsplash.com/photo-1558979158-65a1eaa08691",
    description: "Hilltop castle overlooking the Danube.",
  },
  {
    country: "Slovakia",
    city: "Bratislava",
    name: "Old Town",
    picture: "https://images.unsplash.com/photo-1596464716127-f2a82984de30",
    description: "Historic center with medieval streets.",
  },
  {
    country: "Slovakia",
    city: "Bratislava",
    name: "St. Martin’s Cathedral",
    picture: "https://images.unsplash.com/photo-1600703136783-4a5b6c7d8e9f",
    description: "Gothic cathedral and coronation church.",
  },
  {
    country: "Slovakia",
    city: "Košice",
    name: "St. Elisabeth Cathedral",
    picture: "https://images.unsplash.com/photo-1610986602533-fb25f7f4d8e6",
    description: "Largest church in Slovakia.",
  },
  {
    country: "Slovakia",
    city: "Košice",
    name: "Hlavná Street",
    picture: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e",
    description: "Main pedestrian street.",
  },
  {
    country: "Slovakia",
    city: "Košice",
    name: "East Slovak Museum",
    picture: "https://images.unsplash.com/photo-1587840872194-45f54c59e4a7",
    description: "Oldest museum in Slovakia.",
  },
]

const seedDB = async () => {
  try {
    console.log("Connecting to MongoDB...")
    await mongoose.connect(process.env.MONGODB_URI, {
      serverSelectionTimeoutMS: 5000,
    })
    console.log("MongoDB connected")

    await Attraction.deleteMany({})
    console.log("Old data removed")

    await Attraction.insertMany(attractions)
    console.log("Data seeded successfully")
  } catch (error) {
    console.error("Seeder error:", error)
  } finally {
    await mongoose.connection.close()
    process.exit()
  }
}

seedDB()
